config/routes.rb
Rails.application.routes.draw do
  #ユーザ用 新規登録・ログイン
  devise_for :users, skip: [:passwords], controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions'
  }

  #管理者用　ログイン
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  # ゲストユーザ　ログイン
  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  # 管理者
  namespace :admin do
    resources :users, except: [:new, :create, :destroy]do
      resources :posts, only: [:show, :index, :destroy]
      resources :comments, only: [:index, :destroy]
    end
    resources :tags, except:[:show, :index]
    resources :shop_tags, except:[:index]
  end

	# ユーザ
  scope module: :public do
    get "about" => "homes#about"
     #通知機能
    resources :notifications, only: [:index, :destroy]
    resources :users, only: [:show,:index, :edit, :update] do
      # フォロー機能
      resource :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
      # チャット一覧
      get "chat_rooms"
      #下書き機能
      get "draft_index" => "posts#draft_index"
      member do
      get :likes
      end
    end
    # 投稿機能
    resources :posts do
      #マップ編集
      get "map/edit" => "posts#map_edit"
      #コメント・お気に入り機能
      resources :comments, only: [:create, :destroy]
      resource :likes, only: [:create, :destroy]
    end
    # ユーザの退会確認ページ
    get "user/unsubscribe" => "users#unsubscribe"
    #ユーザ退会処理
    patch "user/withdraw" => "users#withdraw"

    #キーワード検索
    get 'search' => 'searches#search'
    # タグ検索結果ページ
    get "post/tag/:name" => "posts#tag"
    #こだわりタグ検索結果ページ
    get "post/shop_tag/:name" => "posts#shop_tag"
    # チャット機能
    get "chat/:id" => "chats#show", as: "chat"
    resources :chats, only: [:create]
  end
  root to: 'public/homes#top'
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :post_tags, dependent: :destroy
  has_many :posts, through: :post_tags
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < ApplicationController
    before_action :authenticate_admin!
     before_action :tag_choice, only: [:edit, :update, :destroy]
  def new
    @tag = Tag.new
    @tags = Tag.all.order(created_at: "DESC").page(params[:page]).per(20)
  end

  def create
    tag = Tag.new(tag_params)
    if tag.save
      redirect_to request.referer, notice: "タグを新規登録しました。"
    else
      redirect_to request.referer, alert: "タグ登録に失敗しました。"
    end
  end

  def edit
    @tags = Tag.all.order(created_at: "DESC").page(params[:page]).per(20)
  end

  def update
    if @tag.update(tag_params)
      redirect_to new_admin_tag_path, notice: "ハッシュタグ名を更新しました。"
    else
      redirect_to request.referer, alert: "編集内容をご確認ください。"
    end
  end

  def destroy
    @tag.destroy
    redirect_to request.referer, notice: "ハッシュタグを削除しました。"
  end

  private
    def tag_params
      params.require(:tag).permit(:name)
    end

    def tag_choice
      @tag = Tag.find(params[:id])
    end
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/views/admin/tags/_tags.html.erb
<table class="table table-border">
  <thead>
    <tr>
      <th>ハッシュタグ名</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% tags.each do |tag| %>
      <tr>
        <td><%= tag.name %></td>
        <td><%= link_to "編集する", edit_admin_tag_path(tag) %></td>
        <td><%= link_to "削除する", admin_tag_path(tag), method: :delete, data: {confirm: "本当に削除しますか？" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/tags/edit.html.erb
<div class="container">
  <div class="row d-flex justify-content-center">
    <div class="col-lg-8">
      <div class="m-3">
        <h5 class="text-center"><i class="fas fa-cog"></i>こだわりタグ編集</h5>
        <%= form_with model: @tag, url: admin_tag_path(@tag), method: :patch do |f| %>
          <i class="fas fa-tag"></i> <%= f.label :name, "こだわりタグ名" %><br />
          <%= f.text_field :name %>
          <%= f.submit "変更する", class: "btn btn-outline-success" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/tags/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 my-3">
    <h4><i class="fas fa-tag"></i> ハッシュタグを作成</h4>
    <%= form_with model: @tag, url: admin_tags_path, method: :post do |f| %>
     <%= f.label :name, "ハッシュタグ名" %><br>
      <div class="form-group">
       <%= f.text_field :name %><br>
      </div>
     <%= f.submit'登録する', class: "btn btn-success w-50" %>
    <% end %>
    </div>
    <div class="col-md-6 my-3">
    <h4><i class="fas fa-tags"></i> ハッシュタグを編集・削除</h4>
     <table class="table table-border">
       <%= render "tags", tags: @tags %>
    </div>
  </div>
</div>