config/routes.rb
Rails.application.routes.draw do
  #ユーザ用 新規登録・ログイン
  devise_for :users, skip: [:passwords], controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions'
  }

  #管理者用　ログイン
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  # ゲストユーザ　ログイン
  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  # 管理者
  namespace :admin do
    resources :users, except: [:new, :create, :destroy]do
      resources :posts, only: [:show, :index, :destroy]
      resources :comments, only: [:index, :destroy]
    end
    resources :tags, except:[:show, :index]
    resources :shop_tags, except:[:index]
  end

	# ユーザ
  scope module: :public do
    get "about" => "homes#about"
     #通知機能
    resources :notifications, only: [:index, :destroy]
    resources :users, only: [:show,:index, :edit, :update] do
      # フォロー機能
      resource :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
      # チャット一覧
      get "chat_rooms"
      #下書き機能
      get "draft_index" => "posts#draft_index"
      member do
      get :likes
      end
    end
    # 投稿機能
    resources :posts do
      #マップ編集
      get "map/edit" => "posts#map_edit"
      #コメント・お気に入り機能
      resources :comments, only: [:create, :destroy]
      resource :likes, only: [:create, :destroy]
    end
    # ユーザの退会確認ページ
    get "user/unsubscribe" => "users#unsubscribe"
    #ユーザ退会処理
    patch "user/withdraw" => "users#withdraw"

    #キーワード検索
    get 'search' => 'searches#search'
    # タグ検索結果ページ
    get "post/tag/:name" => "posts#tag"
    #こだわりタグ検索結果ページ
    get "post/shop_tag/:name" => "posts#shop_tag"
    # チャット機能
    get "chat/:id" => "chats#show", as: "chat"
    resources :chats, only: [:create]
  end
  root to: 'public/homes#top'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts,    dependent: :destroy
  has_many :likes,    dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_many :user_rooms
  has_many :chats
  has_many :rooms, through: :user_rooms

  has_many :active_notifications, foreign_key: :visitor_id, class_name: "Notification", dependent: :destroy
  has_many :passive_notifications, foreign_key: :visited_id, class_name: "Notification", dependent: :destroy

  validates :name, presence: true, length: { maximum: 20 }
  validates :email,presence: true

   # アイコン画像設定
  has_one_attached :image
  def get_image
    unless image.attached?
      file_path = Rails.root.join("app/assets/images/no_image.jpg")
      image.attach(io: File.open(file_path), filename: "no_image.jpg", content_type: "image/jpeg")
    end
    image
  end

  #退会ユーザはログインできないようにする
  def active_for_authentication?
    super && (self.status == false)
  end

  # フォロー機能
  # フォローする
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  # フォロー解除
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end

  #通知機能（フォロー）
  def create_notification_follow!(current_user)
    #すでに通知が作成されているか確認
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ? ",current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end

  # ゲストログイン機能
   def self.guest
    find_or_create_by!(name: 'guestuser', email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = 'guestuser'
    end
   end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @users = User.all
  end

  def show
     @user = User.find(params[:id])
  end
  def edit
    @user = User.find(params[:id])
  end
  def update
    user = User.find(params[:id])
    user.update(user_params)
    redirect_to admin_users_path
  end

  def user_params
    params.require(:user).permit(:name,:email, :status)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<div class ="container" >
  <div class="row">
    <div class='col-md-8'>
    <h4 class="my-4"><i class="fas fa-user-edit"></i>ユーザー編集</h4>
      <%= form_with model: @user,url: admin_user_path(@user), method: :PATCH do |f|  %>
      <%= f.label :"名前" %><br>
      <%= f.text_field :name %> <br>
      <%= f.label :email,"メールアドレス" %><br>
      <%= f.text_field :email %><br>
      <%= f.radio_button :status, "false" %>
      <%= f.label :status, "有効", value: false %>
      <%= f.radio_button :status, "true" %>
      <%= f.label :status, "退会", value: true %><br>
      <%= f.submit '変更する', class: "btn btn-success w-25" %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="container">
  <div class="row">
    <div class='col-12'>
      <h4 class="my-4"><i class="fas fa-users"></i>ユーザ一覧</h4>
      <table class="table table-hover">
        <thead class="table-area">
          <tr>
          <th>名前</th>
          <th>メールアドレス</th>
          <th>ユーザーステータス</th>
          <th></th>
          <th></th>
          </tr>
        </thead>
        <tbody>
         <% @users.each do |user| %>
          <tr>
            <td>
               <%= user.name %>
            </td>
            <td><%= user.email%></td>
            <td><% if user.status == false %>
                  <p class="text-success font-weight-bold">有効</p>
                <% else %>
                  <p class="text-secondary font-weight-bold">退会</p>
                <% end %>
            </td>
            <td><%= link_to '編集', edit_admin_user_path(user) %></td>
            <td> <%= link_to '詳細', admin_user_path(user), class: "btn btn-block btn-outline-dark" %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="container">
  <div class="row d-flex align-items-center">
    <div class="col-12 ">
      <h4><i class="fas fa-user"></i>ユーザー詳細</h4>
        <i class="fas fa-user-circle"></i> 名前
        <p><%= @user.name %></p>
        <i class="far fa-file-alt"></i> 自己紹介文
        <p><%= @user.introduction %></p>
        <i class="fas fa-envelope"></i> メールアドレス
        <p><%= @user.email %></p>
        <p><%= link_to edit_admin_user_path(@user), class: "btn btn-outline-success w-50" do %>
            編集
           <% end %></p>
        <p><%= link_to admin_user_posts_path(@user), class: "btn btn-outline-dark w-50" do %>
            投稿一覧 (<%= @user.posts.count %>)
          <% end %></p>
        <p><%= link_to admin_user_comments_path(@user), class: "btn btn-outline-dark w-50" do %>
            コメント一覧 (<%= @user.comments.count %>)
          <% end %></p>
    </div>
  </div>
</div>