config/routes.rb
Rails.application.routes.draw do
  #ユーザ用 新規登録・ログイン
  devise_for :users, skip: [:passwords], controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions'
  }

  #管理者用　ログイン
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  # ゲストユーザ　ログイン
  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  # 管理者
  namespace :admin do
    resources :users, except: [:new, :create, :destroy]do
      resources :posts, only: [:show, :index, :destroy]
      resources :comments, only: [:index, :destroy]
    end
    resources :tags, except:[:show, :index]
    resources :shop_tags, except:[:index]
  end

	# ユーザ
  scope module: :public do
    get "about" => "homes#about"
     #通知機能
    resources :notifications, only: [:index, :destroy]
    resources :users, only: [:show,:index, :edit, :update] do
      # フォロー機能
      resource :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
      # チャット一覧
      get "chat_rooms"
      #下書き機能
      get "draft_index" => "posts#draft_index"
      member do
      get :likes
      end
    end
    # 投稿機能
    resources :posts do
      #マップ編集
      get "map/edit" => "posts#map_edit"
      #コメント・お気に入り機能
      resources :comments, only: [:create, :destroy]
      resource :likes, only: [:create, :destroy]
    end
    # ユーザの退会確認ページ
    get "user/unsubscribe" => "users#unsubscribe"
    #ユーザ退会処理
    patch "user/withdraw" => "users#withdraw"

    #キーワード検索
    get 'search' => 'searches#search'
    # タグ検索結果ページ
    get "post/tag/:name" => "posts#tag"
    #こだわりタグ検索結果ページ
    get "post/shop_tag/:name" => "posts#shop_tag"
    # チャット機能
    get "chat/:id" => "chats#show", as: "chat"
    resources :chats, only: [:create]
  end
  root to: 'public/homes#top'
end

app/views/layouts/_footer.html.erb
<footer class="mt-5 pt-5">
    <a href="https://twitter.com/" target="_blank" rel="noopener noreferrer" class="text-light"><i class="fab fa-twitter"></i></a>
    <a href="https://www.instagram.com/" target="_blank" rel="noopener noreferrer" class="text-light"><i class="fab fa-instagram fa-lg"></i></a>
    <a href="https://ja-jp.facebook.com/" target="_blank" rel="noopener noreferrer" class="text-light"><i class="fab fa-facebook"></i></a>
  <p>© 2022 Cafe_chercher</p>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #300;">
    <div class="container">
      <a class="navbar-brand" href="/">
        <%= image_tag 'logo1.jpg', class: 'img-fluid' %>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>

          <li>
            <%= link_to user_path(current_user),class: 'nav-link text-light' do %>
              <i class="fas fa-home"></i>マイページ
            <% end %>
          </li>
          <li>
            <%= link_to users_path, class: 'nav-link text-light' do %>
              <i class="fas fa-users"></i> ユーザ一覧
            <% end %>
          </li>
          <li>
            <%= link_to new_post_path,class: 'nav-link text-light', data: {"turbolinks" => false} do %>
              <i class="fas fa-pen"></i>投稿する
            <% end %>
          </li>
          <li>
            <%=  link_to posts_path ,class: 'nav-link text-light', data: {"turbolinks" => false} do %>
              <i class="fas fa-search"></i>投稿を見る
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete,class: 'nav-link text-light' do %>
              <i class="fas fa-sign-out-alt"></i> ログアウト
            <% end %>
          </li>
           <!--アドミンログイン時-->
        <% elsif admin_signed_in? %>
          <li>
            <%= link_to admin_users_path, class: 'nav-link text-light' do %>
              <i class="fas fa-users-cog fas-xs"></i> ユーザ一覧
            <% end %>
          </li>
          <li>
            <%= link_to new_admin_tag_path, class: 'nav-link text-light' do %>
              <i class="fas fa-tags"></i>タグ管理
            <% end %>
          </li>
           <li>
            <%= link_to new_admin_shop_tag_path, class: 'nav-link text-light' do %>
              <i class="fas fa-tags"></i>こだわりタグ管理
            <% end %>
          </li>
          <li>
            <%= link_to destroy_admin_session_path, method: :delete, class: 'nav-link text-light' do %>
              <i class="fas fa-sign-out-alt"></i> ログアウト
            <% end %>
          </li>
        <!--未ログイン時-->
        <% else %>
          <li>
            <%= link_to about_path, class: 'nav-link text-light' do %>
              <i class="fas fa-coffee"></i> サイト紹介
            <% end %>
          </li>
          <li>
            <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
              <i class="fas fa-user-plus"></i> 新規登録
            <% end %>
          </li>
          <li>
            <%= link_to new_user_session_path, class: 'nav-link text-light' do %>
              <i class="fas fa-sign-in-alt"></i> ログイン
            <% end %>
          </li>
            <li>
            <%= link_to users_guest_sign_in_path, method: :post, class: 'nav-link text-light' do %>
              <i class="fas fa-user-check"></i> ゲストログイン
            <% end %>
          </li>
            </ul>
          </div>
          </nav>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CafeChercher</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="main">
    <%= render 'public/searches/form' %>
    <div class="text-center"><%= notice %></div>
    <div class="text-center"><%= alert %></div>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>